"""Optional YOLO fish detection and crop generation."""

import argparse
import threading
import time
from contextlib import nullcontext
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

from .image_quality import Image, ImageOps, pillow_available, save_pil_image

DETECTOR_LOCK = threading.Lock()
DETECTOR_MODEL = None
DETECTOR_MODEL_PATH = None
SAM3_LOCK = threading.Lock()
SAM3_MODEL = None
SAM3_MODEL_DEVICE = None
SAM3_MODEL_CHECKPOINT_PATH = None
SAM3_MODEL_DTYPE = None
SAM3_MODEL_AUTOCAST = None


@dataclass
class DetectionOutput:
    """One accepted crop generated by a detection backend."""

    accepted_path: Path
    status: str
    metrics: dict[str, Any]
    clip_source_path: Path
    instance_index: Optional[int] = None
    instance_count: int = 1
    species_verification: str = "inat_taxon_assumed"
    created_output: bool = False


def get_detector_model(weights_path: str):
    """Load and cache the YOLO detector model."""
    global DETECTOR_MODEL, DETECTOR_MODEL_PATH

    with DETECTOR_LOCK:
        if DETECTOR_MODEL is not None and DETECTOR_MODEL_PATH == weights_path:
            return DETECTOR_MODEL

        try:
            from ultralytics import YOLO
        except Exception as exc:
            raise RuntimeError(_ultralytics_error_message(exc)) from exc

        DETECTOR_MODEL = YOLO(weights_path)
        DETECTOR_MODEL_PATH = weights_path
        return DETECTOR_MODEL


def _ultralytics_error_message(exc: Exception) -> str:
    """Build an actionable Ultralytics import error message."""
    import sys

    return (
        "YOLO detection requires a working Ultralytics install in the "
        f"current Python interpreter ({sys.executable}). Original import "
        f"error: {type(exc).__name__}: {exc}"
    )


def detection_class_allowed(
    class_id: int,
    class_name: str,
    allowed_class_ids: set[int],
    allowed_class_names: set[str],
) -> bool:
    """Return whether a detector class should be treated as fish."""
    if allowed_class_ids and class_id not in allowed_class_ids:
        return False
    if allowed_class_names and class_name.casefold() not in allowed_class_names:
        return False
    return True


def validate_detector_import() -> None:
    """Fail early if Ultralytics cannot import in the active interpreter."""
    try:
        from ultralytics import YOLO  # noqa: F401
    except Exception as exc:
        raise RuntimeError(_ultralytics_error_message(exc)) from exc


def ensure_sam3_model_files(args: argparse.Namespace) -> Path:
    """Ensure SAM 3 model files exist locally and return the checkpoint path."""
    checkpoint_path = _sam3_checkpoint_path(args)
    if checkpoint_path.exists():
        args.sam_checkpoint_path = str(checkpoint_path)
        return checkpoint_path

    model_dir = Path(args.sam_model_dir)
    model_dir.mkdir(parents=True, exist_ok=True)

    try:
        from huggingface_hub import hf_hub_download
    except Exception as exc:
        raise RuntimeError(_sam3_huggingface_error_message(exc)) from exc

    try:
        hf_hub_download(
            repo_id=args.sam_repo_id,
            filename=args.sam_config_filename,
            local_dir=str(model_dir),
        )
        downloaded_checkpoint = hf_hub_download(
            repo_id=args.sam_repo_id,
            filename=args.sam_checkpoint_filename,
            local_dir=str(model_dir),
        )
    except Exception as exc:
        raise RuntimeError(_sam3_huggingface_error_message(exc)) from exc

    checkpoint_path = Path(downloaded_checkpoint)
    args.sam_checkpoint_path = str(checkpoint_path)
    return checkpoint_path


def preload_sam3_model(args: argparse.Namespace) -> Path:
    """Download every SAM 3 weight and build + warm the model before any image work.

    ``ensure_sam3_model_files`` only fetches the main checkpoint/config. SAM 3.1 also
    pulls auxiliary encoder weights (e.g. ``pytorch_model.bin``) when the model is
    *built*, and may fetch the text backbone on the first ``set_text_prompt`` call.
    Building and running one warmup inference here forces all of those downloads to
    happen up front -- and caches the model in the module global so worker threads
    reuse it (no lazy download, no per-thread rebuild race).
    """
    checkpoint_path = ensure_sam3_model_files(args)

    if not pillow_available():
        raise RuntimeError("SAM 3 preload requires Pillow, which is not installed.")

    try:
        from sam3.model.sam3_image_processor import Sam3Processor
        from sam3.model_builder import build_sam3_image_model
    except Exception as exc:
        raise RuntimeError(
            f"SAM 3 package is not importable: {type(exc).__name__}: {exc}"
        ) from exc

    # Use the SAME effective precision the workers resolve, so the cached model
    # matches their get_sam3_model() cache key and is reused as-is.
    effective_dtype, effective_autocast = _resolve_sam_precision(
        args.detector_device, args.sam_dtype, args.sam_autocast
    )
    target_device = _resolve_device(args.detector_device) or "cpu"

    try:
        model = get_sam3_model(
            build_sam3_image_model,
            args.detector_device,
            getattr(args, "sam_checkpoint_path", None),
            effective_dtype,
            effective_autocast,
        )
        # Warmup: run the full set_image -> set_text_prompt path once so the text
        # backbone and any remaining lazy weights are fetched before the run starts.
        processor = Sam3Processor(model, device=target_device)
        warmup_image = Image.new("RGB", (64, 64), color=(127, 127, 127))
        with _sam_inference_context(
            target_device,
            dtype_name=effective_dtype,
            autocast=effective_autocast,
        ):
            state = processor.set_image(warmup_image)
            processor.set_text_prompt(state=state, prompt=args.sam_prompt)
    except Exception as exc:
        raise RuntimeError(
            f"SAM 3 model failed to load/warm up: {type(exc).__name__}: {exc}"
        ) from exc

    return checkpoint_path


def _sam3_checkpoint_path(args: argparse.Namespace) -> Path:
    if getattr(args, "sam_checkpoint_path", None):
        return Path(args.sam_checkpoint_path)
    return Path(args.sam_model_dir) / args.sam_checkpoint_filename


def _sam3_huggingface_error_message(exc: Exception) -> str:
    import sys

    return (
        "SAM model predownload failed. Make sure this Python interpreter "
        f"({sys.executable}) has huggingface_hub installed, your Hugging Face "
        "account has access to the gated SAM repository, and the server is "
        "authenticated with `huggingface-cli login` or HF_TOKEN. Original error: "
        f"{type(exc).__name__}: {exc}"
    )


def run_fish_detection_outputs(
    raw_path: Path,
    accepted_path: Path,
    args: argparse.Namespace,
    max_outputs: Optional[int] = None,
) -> tuple[list[DetectionOutput], Optional[str], dict]:
    """Run the configured detector and return one or more accepted crop outputs."""
    backend = getattr(args, "detection_backend", "yolo")
    if backend == "sam3":
        return run_sam3_detection_outputs(raw_path, accepted_path, args, max_outputs)

    is_detected, reject_reason, metrics = run_fish_detection(raw_path, accepted_path, args)
    if not is_detected:
        return [], reject_reason, metrics

    status = (
        "accepted_crop_existing"
        if metrics.get("saved") == "existing"
        else "accepted_crop"
    )
    return [
        DetectionOutput(
            accepted_path=accepted_path,
            status=status,
            metrics=metrics,
            clip_source_path=accepted_path,
            created_output=bool(metrics.get("created_output")),
        )
    ], None, metrics


def run_fish_detection(
    raw_path: Path,
    accepted_path: Path,
    args: argparse.Namespace,
) -> tuple[bool, Optional[str], dict]:
    """Run YOLO detection, reject bad detections, and save a padded fish crop."""
    if not pillow_available():
        return False, "pillow_not_installed", {"enabled": True}

    if accepted_path.exists() and not args.overwrite:
        return True, None, {
            "enabled": True,
            "saved": "existing",
            "created_output": False,
            "model": args.detector_weights,
        }

    model = get_detector_model(args.detector_weights)
    allowed_class_ids = args.detector_class_id_set
    allowed_class_names = args.detector_class_name_set

    with Image.open(raw_path) as source_image:
        image_format = source_image.format
        image = ImageOps.exif_transpose(source_image)
        if image.mode not in {"RGB", "L"}:
            image = image.convert("RGB")

        width, height = image.size
        image_area = max(width * height, 1)

        predict_kwargs = {
            "source": image,
            "conf": args.detector_confidence,
            "imgsz": args.detector_imgsz,
            "verbose": False,
        }
        if args.detector_device:
            predict_kwargs["device"] = args.detector_device

        with DETECTOR_LOCK:
            results = model.predict(**predict_kwargs)

        result = results[0]
        raw_boxes = []
        if result.boxes is not None:
            xyxy_values = result.boxes.xyxy.cpu().tolist()
            conf_values = result.boxes.conf.cpu().tolist()
            cls_values = result.boxes.cls.cpu().tolist()
            names = result.names or {}

            for xyxy, confidence, class_value in zip(
                xyxy_values, conf_values, cls_values
            ):
                class_id = int(class_value)
                class_name = str(names.get(class_id, class_id))
                if not detection_class_allowed(
                    class_id,
                    class_name,
                    allowed_class_ids,
                    allowed_class_names,
                ):
                    continue

                x1, y1, x2, y2 = [float(value) for value in xyxy]
                box_width = max(0.0, x2 - x1)
                box_height = max(0.0, y2 - y1)
                area_ratio = (box_width * box_height) / image_area
                raw_boxes.append(
                    {
                        "bbox_xyxy": [
                            round(x1, 2),
                            round(y1, 2),
                            round(x2, 2),
                            round(y2, 2),
                        ],
                        "confidence": round(float(confidence), 6),
                        "class_id": class_id,
                        "class_name": class_name,
                        "area_ratio": round(area_ratio, 6),
                        "selection_score": float(confidence) * area_ratio,
                    }
                )

        metrics = {
            "enabled": True,
            "model": args.detector_weights,
            "created_output": False,
            "confidence_threshold": args.detector_confidence,
            "raw_detection_count": int(0 if result.boxes is None else len(result.boxes)),
            "fish_detection_count": len(raw_boxes),
            "min_fish_area_ratio": args.min_fish_area_ratio,
            "crop_padding": args.crop_padding,
            "allowed_class_ids": sorted(allowed_class_ids),
            "allowed_class_names": sorted(allowed_class_names),
        }

        if not raw_boxes:
            return False, "no_fish_detected", metrics

        if len(raw_boxes) > 1 and not args.allow_multiple_fish:
            metrics["detections"] = raw_boxes
            return False, "multiple_fish_detected", metrics

        selected = max(raw_boxes, key=lambda item: item["selection_score"])
        metrics["selected_detection"] = {
            key: value for key, value in selected.items() if key != "selection_score"
        }

        if selected["area_ratio"] < args.min_fish_area_ratio:
            return False, "fish_too_small", metrics

        x1, y1, x2, y2 = selected["bbox_xyxy"]
        box_width = x2 - x1
        box_height = y2 - y1
        pad_x = box_width * args.crop_padding
        pad_y = box_height * args.crop_padding
        crop_box = (
            max(0, int(x1 - pad_x)),
            max(0, int(y1 - pad_y)),
            min(width, int(x2 + pad_x)),
            min(height, int(y2 + pad_y)),
        )
        metrics["crop_box_xyxy"] = list(crop_box)

        crop = image.crop(crop_box)
        save_pil_image(crop, accepted_path, image_format)
        metrics["saved"] = "written"
        metrics["created_output"] = True
        return True, None, metrics


def run_sam3_detection_outputs(
    raw_path: Path,
    accepted_path: Path,
    args: argparse.Namespace,
    max_outputs: Optional[int] = None,
) -> tuple[list[DetectionOutput], Optional[str], dict]:
    """Run SAM 3 text-prompt segmentation and save one crop per selected fish."""
    metrics: dict[str, Any] = {
        "enabled": True,
        "backend": "sam3",
        "model": getattr(args, "sam_repo_id", "sam3"),
        "checkpoint_path": getattr(args, "sam_checkpoint_path", None),
        "dtype": args.sam_dtype,
        "autocast": args.sam_autocast,
        "device": None,
        "prompt": args.sam_prompt,
        "created_output": False,
        "crop_padding": args.sam_crop_padding,
        "score_threshold": args.sam_score_threshold,
        "min_mask_area_ratio": args.sam_min_mask_area_ratio,
        "max_instances_per_image": args.sam_max_instances_per_image,
    }
    if not pillow_available():
        return [], "pillow_not_installed", metrics

    started = time.perf_counter()
    try:
        from sam3.model.sam3_image_processor import Sam3Processor
        from sam3.model_builder import build_sam3_image_model
    except Exception as exc:
        metrics["error"] = f"{type(exc).__name__}: {exc}"
        metrics["inference_seconds"] = round(time.perf_counter() - started, 6)
        return [], "sam3_not_available", metrics

    try:
        target_device = _resolve_device(args.detector_device) or "cpu"
        metrics["device"] = target_device
        effective_dtype, effective_autocast = _resolve_sam_precision(
            args.detector_device, args.sam_dtype, args.sam_autocast
        )
        metrics["dtype"] = effective_dtype
        metrics["autocast"] = effective_autocast
        if args.sam_autocast and not effective_autocast:
            metrics["autocast_fallback"] = (
                f"bfloat16 autocast requested but device '{target_device}' is not CUDA; "
                "falling back to float32 without autocast"
            )
        model = get_sam3_model(
            build_sam3_image_model,
            args.detector_device,
            getattr(args, "sam_checkpoint_path", None),
            effective_dtype,
            effective_autocast,
        )
        processor = Sam3Processor(model, device=target_device)
        with Image.open(raw_path) as source_image:
            image_format = source_image.format
            image = ImageOps.exif_transpose(source_image)
            if image.mode != "RGB":
                image = image.convert("RGB")
            width, height = image.size

            with _sam_inference_context(
                target_device,
                dtype_name=effective_dtype,
                autocast=effective_autocast,
            ):
                state = processor.set_image(image)
                output = processor.set_text_prompt(state=state, prompt=args.sam_prompt)
            raw_instances = select_sam3_instances(
                masks=output.get("masks"),
                boxes=output.get("boxes"),
                scores=output.get("scores"),
                width=width,
                height=height,
                score_threshold=args.sam_score_threshold,
                min_mask_area_ratio=args.sam_min_mask_area_ratio,
                crop_padding=args.sam_crop_padding,
            )
            metrics["raw_detection_count"] = _safe_len(output.get("boxes"))
            source_instance_count = len(raw_instances)

            if not args.sam_save_all_instances and raw_instances:
                raw_instances = raw_instances[:1]
            if args.sam_max_instances_per_image is not None:
                raw_instances = raw_instances[: args.sam_max_instances_per_image]
            if max_outputs is not None:
                raw_instances = raw_instances[:max_outputs]

            metrics["fish_detection_count"] = len(raw_instances)
            metrics["source_instance_count"] = source_instance_count
            metrics["inference_seconds"] = round(time.perf_counter() - started, 6)
            if not raw_instances:
                return [], "no_fish_detected", metrics

            species_verification = (
                "unverified" if source_instance_count > 1 else "inat_taxon_assumed"
            )
            outputs = []
            for index, instance in enumerate(raw_instances, start=1):
                output_path = _instance_path(accepted_path, index)
                instance_metrics = {
                    **metrics,
                    "selected_detection": {
                        "bbox_xyxy": list(instance["bbox_xyxy"]),
                        "score": round(instance["score"], 6),
                        "mask_area_ratio": round(instance["mask_area_ratio"], 6),
                        "crop_box_xyxy": list(instance["crop_box_xyxy"]),
                    },
                    "instance_index": index,
                    "instance_count": source_instance_count,
                    "species_verification": species_verification,
                }

                if output_path.exists() and not args.overwrite:
                    instance_metrics["saved"] = "existing"
                    instance_metrics["created_output"] = False
                    status = "accepted_crop_existing"
                    created_output = False
                else:
                    crop = image.crop(instance["crop_box_xyxy"])
                    save_pil_image(crop, output_path, image_format)
                    instance_metrics["saved"] = "written"
                    instance_metrics["created_output"] = True
                    metrics["created_output"] = True
                    status = "accepted_crop"
                    created_output = True

                outputs.append(
                    DetectionOutput(
                        accepted_path=output_path,
                        status=status,
                        metrics=instance_metrics,
                        clip_source_path=output_path,
                        instance_index=index,
                        instance_count=source_instance_count,
                        species_verification=species_verification,
                        created_output=created_output,
                    )
                )

            return outputs, None, metrics
    except Exception as exc:
        metrics["error"] = f"{type(exc).__name__}: {exc}"
        metrics["inference_seconds"] = round(time.perf_counter() - started, 6)
        return [], "sam3_error", metrics


def get_sam3_model(
    build_sam3_image_model,
    device: Optional[str],
    checkpoint_path: Optional[str] = None,
    dtype_name: str = "float32",
    autocast: bool = False,
):
    """Load and cache the SAM 3 image model."""
    global SAM3_MODEL, SAM3_MODEL_AUTOCAST, SAM3_MODEL_CHECKPOINT_PATH
    global SAM3_MODEL_DEVICE, SAM3_MODEL_DTYPE

    target_device = _resolve_device(device) or "cpu"
    resolved_checkpoint_path = str(checkpoint_path) if checkpoint_path else None
    # Under autocast, keep master weights in float32 and let autocast cast eligible
    # ops (matmul/linear) to the compute dtype on the fly -- this matches Meta's
    # SAM 3 quickstart. Pre-casting the whole model to bf16 breaks the ops autocast
    # leaves in float32, producing "mat1 and mat2 must have the same dtype" errors.
    weight_dtype_name = "float32" if autocast else dtype_name
    torch_dtype = _resolve_sam_torch_dtype(weight_dtype_name)
    with SAM3_LOCK:
        if (
            SAM3_MODEL is not None
            and SAM3_MODEL_DEVICE == target_device
            and SAM3_MODEL_CHECKPOINT_PATH == resolved_checkpoint_path
            and SAM3_MODEL_DTYPE == dtype_name
            and SAM3_MODEL_AUTOCAST == autocast
        ):
            return SAM3_MODEL
        model = build_sam3_image_model(
            checkpoint_path=resolved_checkpoint_path,
            device=target_device,
        )
        if not autocast:
            _disable_sam_internal_bf16_contexts(model)
        if target_device and target_device != "auto" and hasattr(model, "to"):
            model = model.to(device=target_device, dtype=torch_dtype)
        elif hasattr(model, "to"):
            model = model.to(dtype=torch_dtype)
        if hasattr(model, "eval"):
            model.eval()
        SAM3_MODEL = model
        SAM3_MODEL_DEVICE = target_device
        SAM3_MODEL_CHECKPOINT_PATH = resolved_checkpoint_path
        SAM3_MODEL_DTYPE = dtype_name
        SAM3_MODEL_AUTOCAST = autocast
        return model


def select_sam3_instances(
    *,
    masks,
    boxes,
    scores,
    width: int,
    height: int,
    score_threshold: float,
    min_mask_area_ratio: float,
    crop_padding: float,
) -> list[dict[str, Any]]:
    """Select SAM 3 instances that satisfy score and area thresholds."""
    if boxes is None or scores is None or _safe_len(boxes) == 0:
        return []

    box_values = _tensor_to_list(boxes)
    score_values = _tensor_to_list(scores)
    mask_values = _tensor_to_list(masks) if masks is not None else None
    instances = []
    image_area = max(width * height, 1)

    for index, box_value in enumerate(box_values):
        score = float(score_values[index])
        if score < score_threshold:
            continue
        x1, y1, x2, y2 = [float(value) for value in box_value[:4]]
        mask_area_ratio = _mask_area_ratio(mask_values, index)
        if mask_area_ratio is None:
            mask_area_ratio = max(0.0, (x2 - x1) * (y2 - y1)) / image_area
        if mask_area_ratio < min_mask_area_ratio:
            continue

        crop_box = _padded_crop_box(
            (x1, y1, x2, y2),
            width=width,
            height=height,
            padding=crop_padding,
        )
        instances.append(
            {
                "bbox_xyxy": (
                    round(x1, 2),
                    round(y1, 2),
                    round(x2, 2),
                    round(y2, 2),
                ),
                "score": score,
                "mask_area_ratio": mask_area_ratio,
                "crop_box_xyxy": crop_box,
            }
        )

    instances.sort(key=lambda item: item["score"], reverse=True)
    return instances


def _instance_path(path: Path, index: int) -> Path:
    return path.with_name(f"{path.stem}__inst_{index}{path.suffix}")


def _resolve_device(device: Optional[str]) -> Optional[str]:
    if not device or device == "auto":
        try:
            import torch
        except Exception:
            return None
        if torch.cuda.is_available():
            return "cuda"
        if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
            return "mps"
        return "cpu"
    return device


def _resolve_sam_precision(
    device: Optional[str], dtype_name: str, autocast: bool
) -> tuple[str, bool]:
    """Resolve the effective (dtype, autocast) for SAM 3, guarding non-CUDA devices.

    SAM 3 / 3.1 is designed to run under bfloat16 autocast on CUDA. That path is
    unsupported on MPS and unhelpful on CPU, so when autocast is requested off CUDA
    we fall back to plain float32 (no autocast) to avoid bf16/float matmul errors.
    """
    if not autocast:
        return dtype_name, False
    device_type = (_resolve_device(device) or "cpu").split(":", 1)[0]
    if device_type != "cuda":
        return "float32", False
    return dtype_name, True


def _resolve_sam_torch_dtype(dtype_name: str):
    import torch

    dtype_map = {
        "float32": torch.float32,
        "float16": torch.float16,
        "bfloat16": torch.bfloat16,
    }
    try:
        return dtype_map[dtype_name]
    except KeyError as exc:
        raise ValueError(
            "SAM dtype must be one of: float32, float16, bfloat16"
        ) from exc


def _sam_inference_context(device: Optional[str], *, dtype_name: str, autocast: bool):
    try:
        import torch
    except Exception:
        return nullcontext()

    device_type = (device or "cpu").split(":", 1)[0]
    try:
        if not autocast:
            return torch.autocast(device_type=device_type, enabled=False)
        return torch.autocast(
            device_type=device_type,
            dtype=_resolve_sam_torch_dtype(dtype_name),
            enabled=True,
        )
    except (RuntimeError, ValueError):
        return nullcontext()


def _disable_sam_internal_bf16_contexts(model) -> int:
    """Exit SAM's long-lived BF16 autocast contexts when stable float inference is requested."""
    disabled = 0
    modules = model.modules() if hasattr(model, "modules") else [model]
    for module in modules:
        context = getattr(module, "bf16_context", None)
        if context is None or not hasattr(context, "__exit__"):
            continue
        try:
            context.__exit__(None, None, None)
        except RuntimeError:
            continue
        else:
            disabled += 1
            try:
                module.bf16_context = nullcontext()
            except Exception:
                pass
    return disabled


def _padded_crop_box(
    box: tuple[float, float, float, float],
    *,
    width: int,
    height: int,
    padding: float,
) -> tuple[int, int, int, int]:
    x1, y1, x2, y2 = box
    box_width = max(0.0, x2 - x1)
    box_height = max(0.0, y2 - y1)
    pad_x = box_width * padding
    pad_y = box_height * padding
    return (
        max(0, int(x1 - pad_x)),
        max(0, int(y1 - pad_y)),
        min(width, int(x2 + pad_x)),
        min(height, int(y2 + pad_y)),
    )


def _mask_area_ratio(mask_values, index: int) -> Optional[float]:
    if mask_values is None:
        return None
    flat_mask = _flatten(mask_values[index])
    if not flat_mask:
        return None
    return sum(1 for value in flat_mask if float(value) > 0) / len(flat_mask)


def _safe_len(value) -> int:
    if value is None:
        return 0
    try:
        return len(value)
    except TypeError:
        return int(value.shape[0]) if hasattr(value, "shape") else 0


def _tensor_to_list(value):
    if hasattr(value, "detach"):
        value = value.detach()
    if hasattr(value, "cpu"):
        value = value.cpu()
    if hasattr(value, "tolist"):
        return value.tolist()
    return value


def _flatten(values):
    if not isinstance(values, list):
        return [values]
    flattened = []
    for value in values:
        flattened.extend(_flatten(value))
    return flattened
